### ISSUE TITLE
Set internationalization mechanism

### ISSUE THREAD

**Issue by MihaMarkic** [sledilnik/mobile-app#7]
We have to put up a proper internationalization mechanism and provide strings and formatting through it. Number and date formating already uses it though the locale is hardcoded for now.

**Comment by stefanb** [comment]
We can use Weblate for translations:
https://docs.weblate.org/en/latest/formats.html#aresource

**Comment by MihaMarkic** [comment]
I guess whatever tool that generates i10n, right? I will set up flutter stuff for consuming it.

**Comment by stefanb** [comment]
Otoh flutter seems to have it a bit differently:
https://flutter.dev/docs/development/accessibility-and-localization/internationalization

But we can also use Weblate for .arb files
https://docs.weblate.org/en/latest/formats.html#arb

**Comment by MihaMarkic** [comment]
@stefanb Version that has localization at its core is now in main branch, also updated readme. Can you give it a try with Weblate?

**Comment by stefanb** [comment]
Weblate project configured: https://hosted.weblate.org/projects/sledilnik/mobile-app/

Base language is english, so make sure to add the strings at least into `sledilnik_mobile_app/lib/l10n/app_en.arb`.

Webhook is configured, so changes in the git repo should come to weblate immediately.
Changes from weblate will be committed and pushed to git an hour after the last change, so that not every change has its own commit.

You can use your GitHub account or create login on Weblate, or make sure that your Weblate account has one of the email addresses you have in your GitHub profile, so your contributions are attributed properly.

**Comment by stefanb** [comment]
FYI, the app is always shown in slovenian

**Comment by MihaMarkic** [comment]
@stefanb yep, always in Slovene for now. It needs a page to select the language and automatic language selection upon start based on OS settings.
